In [171]:
import pandas as pd
import numpy as np

In [172]:
ts1 = pd.Series(np.random.randn(9), index=[
     ['a','a','a','b','b','c','c','d','d'],
     [ 1,  2,  3,  1,  3,  1,  2,  2,  3]                                      
])

In [173]:
ts1

a  1   -1.416192
   2   -0.850841
   3   -0.018083
b  1   -0.298037
   3    0.052336
c  1    0.293845
   2   -1.170683
d  2   -0.035933
   3    0.130643
dtype: float64

In [174]:
ts1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [175]:
ts1['a']

1   -1.416192
2   -0.850841
3   -0.018083
dtype: float64

In [176]:
ts1['b']

1   -0.298037
3    0.052336
dtype: float64

In [177]:
ts1['b':'c']

b  1   -0.298037
   3    0.052336
c  1    0.293845
   2   -1.170683
dtype: float64

In [178]:
ts1.loc[['b','d']]

b  1   -0.298037
   3    0.052336
d  2   -0.035933
   3    0.130643
dtype: float64

In [179]:
ts1.loc[:,2]

a   -0.850841
c   -1.170683
d   -0.035933
dtype: float64

In [180]:
ts1

a  1   -1.416192
   2   -0.850841
   3   -0.018083
b  1   -0.298037
   3    0.052336
c  1    0.293845
   2   -1.170683
d  2   -0.035933
   3    0.130643
dtype: float64

In [181]:
df1 = ts1.unstack()

In [182]:
df1

,1,2,3
a,-1.416192,-0.850841,-0.018083
b,-0.298037,NaN,0.052336
c,0.293845,-1.170683,NaN
d,NaN,-0.035933,0.130643


In [183]:
ts2 = df1.stack()

In [184]:
ts2

a  1   -1.416192
   2   -0.850841
   3   -0.018083
b  1   -0.298037
   2         NaN
   3    0.052336
c  1    0.293845
   2   -1.170683
   3         NaN
d  1         NaN
   2   -0.035933
   3    0.130643
dtype: float64

In [185]:
ts1.unstack().stack()

a  1   -1.416192
   2   -0.850841
   3   -0.018083
b  1   -0.298037
   2         NaN
   3    0.052336
c  1    0.293845
   2   -1.170683
   3         NaN
d  1         NaN
   2   -0.035933
   3    0.130643
dtype: float64

In [186]:
ts1

a  1   -1.416192
   2   -0.850841
   3   -0.018083
b  1   -0.298037
   3    0.052336
c  1    0.293845
   2   -1.170683
d  2   -0.035933
   3    0.130643
dtype: float64

In [187]:
ts1.index.names = ['k1', 'k2']

In [188]:
ts1

k1  k2
a   1    -1.416192
    2    -0.850841
    3    -0.018083
b   1    -0.298037
    3     0.052336
c   1     0.293845
    2    -1.170683
d   2    -0.035933
    3     0.130643
dtype: float64

In [189]:
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'],[1,2,1,2]], columns=[['marmara','marmara','ege'],['istanbul','tekirdag','izmir']])

In [190]:
df2

marmara            ege
    istanbul tekirdag izmir
a 1        0        1     2
  2        3        4     5
b 1        6        7     8
  2        9       10    11

In [191]:
df2['marmara']

istanbul  tekirdag
a 1         0         1
  2         3         4
b 1         6         7
  2         9        10

In [192]:
df2.index.names = ['k1', 'k2']

In [193]:
df2

marmara            ege
      istanbul tekirdag izmir
k1 k2                        
a  1         0        1     2
   2         3        4     5
b  1         6        7     8
   2         9       10    11

In [194]:
df2.columns.names=['region','city']

In [195]:
df2

region  marmara            ege
city   istanbul tekirdag izmir
k1 k2                         
a  1          0        1     2
   2          3        4     5
b  1          6        7     8
   2          9       10    11

In [196]:
df3 = pd.DataFrame({
    'key': ['b','b','a','c','a','a','b'],
    'data1': range(7)
})
df4 = pd.DataFrame({
    'key': ['a','b','d'],
    'data2': range(3)
})

In [197]:
df3

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,a,5
6,b,6


In [198]:
df4

,key,data2
0,a,0
1,b,1
2,d,2


In [199]:
df5 = pd.merge(df3,df4,on = "key")

In [200]:
df5

,key,data1,data2
0,b,0,1
1,b,1,1
2,a,2,0
3,a,4,0
4,a,5,0
5,b,6,1


In [201]:
df6 = pd.merge(df3,df4,how="outer")

In [202]:
df6

,key,data1,data2
0,a,2.0,0.0
1,a,4.0,0.0
2,a,5.0,0.0
3,b,0.0,1.0
4,b,1.0,1.0
5,b,6.0,1.0
6,c,3.0,NaN
7,d,NaN,2.0


In [203]:
df7 = pd.merge(df3,df4,how="left")

In [204]:
df7

,key,data1,data2
0,b,0,1.0
1,b,1,1.0
2,a,2,0.0
3,c,3,NaN
4,a,4,0.0
5,a,5,0.0
6,b,6,1.0


In [205]:
df8 = pd.merge(df3,df4,how="right")

In [206]:
df8

,key,data1,data2
0,a,2.0,0
1,a,4.0,0
2,a,5.0,0
3,b,0.0,1
4,b,1.0,1
5,b,6.0,1
6,d,NaN,2


In [207]:
arr1 = np.arange(12).reshape((3,4))
arr4 = np.arange(12).reshape((4,3))

In [208]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [209]:
arr2 = np.concatenate([arr1, arr1], axis=0)

In [210]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
arr3 = np.concatenate([arr1, arr1], axis=1)

In [212]:
arr3

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [213]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [214]:
try:
  arr5 = np.concatenate([arr1, arr4], axis=0)
except ValueError as err:
  print(err)  

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3


In [215]:
ts3 = pd.Series([0,1], index=['a','b'])
ts4 = pd.Series([2,3,4], index=['c','d','e'])
ts5 = pd.Series([5,6], index=['f','g'])

In [216]:
ts6 = pd.concat([ts3, ts4, ts5], axis=0)

In [217]:
ts6

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [218]:
ts3 = pd.Series([0,1,42], index=['a','b','c'])
ts4 = pd.Series([2,3,4], index=['c','d','e'])
ts5 = pd.Series([108, 5,6], index=['c','f','g'])

In [219]:
ts7 = pd.concat([ts3, ts4, ts5], axis=1, join='inner')

In [220]:
ts7

,0,1,2
c,42,2,108


In [221]:
countries_df = pd.read_json("sample_data/countries.json")

In [222]:
countries_df.columns

Index(['capital', 'cities', '_id', 'continent', 'gnp', 'governmentForm',
       'headOfState', 'lifeExpectancy', 'localName', 'name', 'population',
       'region', 'surfaceArea', 'indepYear'],
      dtype='str')

In [223]:
del countries_df['cities']

In [224]:
countries_df.head(5)

,capital,_id,continent,gnp,governmentForm,headOfState,lifeExpectancy,localName,name,population,region,surfaceArea,indepYear
0,129.0,ABW,North America,828.0,Nonmetropolitan Territory of The Netherlands,Beatrix,78.4,Aruba,Aruba,103000,Caribbean,205.0,NaN
1,1.0,AFG,Asia,5976.0,Islamic Emirate,Mohammad Omar,45.9,Afganistan/Afqanestan,Afghanistan,22720000,Southern and Central Asia,652102.0,1919.0
2,56.0,AGO,Africa,6648.0,Republic,José Eduardo dos Santos,38.3,Angola,Angola,12878000,Central Africa,1246712.0,1975.0
3,62.0,AIA,North America,63.2,Dependent Territory of the UK,Elisabeth II,76.1,Anguilla,Anguilla,8000,Caribbean,108.0,NaN
4,34.0,ALB,Europe,3205.0,Republic,Rexhep Mejdani,71.6,Shqipëria,Albania,3401200,Southern Europe,28760.0,1912.0


In [225]:
countries_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   capital         232 non-null    float64
 1   _id             239 non-null    str    
 2   continent       239 non-null    str    
 3   gnp             239 non-null    float64
 4   governmentForm  239 non-null    str    
 5   headOfState     238 non-null    str    
 6   lifeExpectancy  222 non-null    float64
 7   localName       239 non-null    str    
 8   name            239 non-null    str    
 9   population      239 non-null    int64  
 10  region          239 non-null    str    
 11  surfaceArea     239 non-null    float64
 12  indepYear       192 non-null    float64
dtypes: float64(5), int64(1), str(7)
memory usage: 24.4 KB


In [226]:
ulkeler = countries_df.dropna()

In [227]:
ulkeler.info()

<class 'pandas.DataFrame'>
Index: 190 entries, 1 to 238
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   capital         190 non-null    float64
 1   _id             190 non-null    str    
 2   continent       190 non-null    str    
 3   gnp             190 non-null    float64
 4   governmentForm  190 non-null    str    
 5   headOfState     190 non-null    str    
 6   lifeExpectancy  190 non-null    float64
 7   localName       190 non-null    str    
 8   name            190 non-null    str    
 9   population      190 non-null    int64  
 10  region          190 non-null    str    
 11  surfaceArea     190 non-null    float64
 12  indepYear       190 non-null    float64
dtypes: float64(5), int64(1), str(7)
memory usage: 20.8 KB


In [228]:
df10 = pd.DataFrame({
    "key": ["jack", "kate", "james"],
    "age": [48, 39, 42],
    "salary": [100_000, 200_000, 300_000],
    "department": ["IT", "SALES", "FINANCE"] 
})

In [229]:
df10

,key,age,salary,department
0,jack,48,100000,IT
1,kate,39,200000,SALES
2,james,42,300000,FINANCE


In [230]:
melted_df = pd.melt(df10, ["key"])

In [231]:
melted_df

,key,variable,value
0,jack,age,48
1,kate,age,39
2,james,age,42
3,jack,salary,100000
4,kate,salary,200000
5,james,salary,300000
6,jack,department,IT
7,kate,department,SALES
8,james,department,FINANCE


In [232]:
melted_df2 = pd.melt(df10, ["department"])

In [233]:
melted_df2[melted_df2.department == 'IT']

,department,variable,value
0,IT,key,jack
3,IT,age,48
6,IT,salary,100000


In [234]:
melted_df[melted_df.key == 'jack']

,key,variable,value
0,jack,age,48
3,jack,salary,100000
6,jack,department,IT


In [235]:
countries_df

,capital,_id,continent,gnp,governmentForm,headOfState,lifeExpectancy,localName,name,population,region,surfaceArea,indepYear
0,129.0,ABW,North America,828.0,Nonmetropolitan Territory of The Netherlands,Beatrix,78.4,Aruba,Aruba,103000,Caribbean,205.0,NaN
1,1.0,AFG,Asia,5976.0,Islamic Emirate,Mohammad Omar,45.9,Afganistan/Afqanestan,Afghanistan,22720000,Southern and Central Asia,652102.0,1919.0
2,56.0,AGO,Africa,6648.0,Republic,José Eduardo dos Santos,38.3,Angola,Angola,12878000,Central Africa,1246712.0,1975.0
3,62.0,AIA,North America,63.2,Dependent Territory of the UK,Elisabeth II,76.1,Anguilla,Anguilla,8000,Caribbean,108.0,NaN
4,34.0,ALB,Europe,3205.0,Republic,Rexhep Mejdani,71.6,Shqipëria,Albania,3401200,Southern Europe,28760.0,1912.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,1780.0,YEM,Asia,6041.0,Republic,Ali Abdallah Salih,59.8,Al-Yaman,Yemen,18112000,Middle East,527980.0,1918.0
235,1792.0,YUG,Europe,17000.0,Federal Republic,Vojislav Koštunica,72.4,Jugoslavija,Yugoslavia,10640000,Southern Europe,102185.0,1918.0
236,716.0,ZAF,Africa,116729.0,Republic,Thabo Mbeki,51.1,South Africa,South Africa,40377000,Southern Africa,1221049.0,1910.0
237,3162.0,ZMB,Africa,3377.0,Republic,Frederick Chiluba,37.2,Zambia,Zambia,9169000,Eastern Africa,752630.0,1964.0


In [236]:
melted_countries = pd.melt(countries_df, ["_id"] )

In [237]:
melted_countries.head(10)

,_id,variable,value
0,ABW,capital,129.0
1,AFG,capital,1.0
2,AGO,capital,56.0
3,AIA,capital,62.0
4,ALB,capital,34.0
5,AND,capital,55.0
6,ANT,capital,33.0
7,ARE,capital,65.0
8,ARG,capital,69.0
9,ARM,capital,126.0
