In [10]:
#!pip install numpy
import numpy as np # c library
print(np.__version__)

2.4.5


In [11]:
# "numeric python" -> numpy
# 1. Fast (implemented in C)
# 2. element-wise: /,*,+,... 
# 3. homogeneous: int, float, str, ...

In [12]:
mylist = list(range(10_000_000)) # python's list

In [13]:
arr = np.arange(10_000_000) # numpy array

In [14]:
%time for i in range(10): arr2 = arr * 2  

CPU times: total: 156 ms
Wall time: 163 ms


In [15]:
%time for i in range(10): mylist2 = [x*2 for x in mylist]

CPU times: total: 4.34 s
Wall time: 4.42 s


In [16]:
arr3 = 2 * arr + arr

In [17]:
numbers = [4,8,15,16,23,42]

In [18]:
numbers * 4

[4,
 8,
 15,
 16,
 23,
 42,
 4,
 8,
 15,
 16,
 23,
 42,
 4,
 8,
 15,
 16,
 23,
 42,
 4,
 8,
 15,
 16,
 23,
 42]

In [19]:
[x*2 for x in numbers]

[8, 16, 30, 32, 46, 84]

In [20]:
numbers + numbers

[4, 8, 15, 16, 23, 42, 4, 8, 15, 16, 23, 42]

In [21]:
arr4 = np.array([4,8,15,16,23,42])

In [22]:
arr4 // 2

array([ 2,  4,  7,  8, 11, 21])

In [23]:
data1 = np.random.randn(3,4)

In [24]:
type(data1)

numpy.ndarray

In [25]:
data2 = np.array([[1,2.,3],[4,5,6]])

In [26]:
type(data2)

numpy.ndarray

In [27]:
data1.shape

(3, 4)

In [28]:
data2.shape

(2, 3)

In [29]:
data1.dtype

dtype('float64')

In [30]:
data2.dtype

dtype('float64')

In [31]:
data3 = np.array([True, False, False, True])

In [32]:
data3.dtype

dtype('bool')

In [33]:
data4 = np.array(["jack", "kate", "james", "ben"])

In [34]:
data4.dtype

dtype('<U5')

In [35]:
# numpy array: dtype, shape, ndim

In [36]:
data1.dtype

dtype('float64')

In [37]:
data1.shape

(3, 4)

In [38]:
data1.ndim

2

In [39]:
data5 = np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])

In [40]:
print(data5.dtype, data5.shape, data5.ndim)

int64 (2, 2, 3) 3


In [41]:
#1 list   -> np.array([1,2,3])
#2 random -> np.random.randint(3,4,5)
#3 0 , 1  -> np.zeros((3,4,5)), np.ones((3,4,5))

In [42]:
data6 = np.zeros((3,4,5))

In [43]:
data6

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
data7 = np.ones((3,4,5))

In [45]:
data7

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [48]:
data8 = np.array(['U20BA', 2, 3], dtype=np.str_)

In [49]:
data8.dtype

dtype('<U5')

In [51]:
data9 = np.array([2, 2, 3, 1_000_000], dtype=np.int32)

In [54]:
data9.dtype

dtype('int32')

In [53]:
data9

array([      2,       2,       3, 1000000], dtype=int32)

In [52]:
data11 = data9.astype(np.float64)

In [55]:
data11.dtype

dtype('float64')

In [56]:
data10 = np.array([2, 2, 3])

In [57]:
data10.dtype

dtype('int64')