In [4]:
import numpy as np # c library
print(np.__version__)

2.4.5


In [5]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]]) 

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr1.ndim

2

In [8]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
# 1. vectorization: element-wise
arr1 * arr1

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
arr1 - arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [12]:
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [13]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [14]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [16]:
arr2 != arr1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [17]:
# 2. Indexing [2] & Slicing[start:stop:step]
name = "jack bauer"

In [18]:
print(name[0],name[-1],len(name))

j r 10


In [19]:
name[0:4]

'jack'

In [20]:
name[:4]

'jack'

In [21]:
name[4:]

' bauer'

In [22]:
name[::2]

'jc ae'

In [23]:
name[::-1]

'reuab kcaj'

In [24]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]]) 
arr3 = np.arange(10)

In [25]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr3[6]

np.int64(6)

In [27]:
arr3[3:7] # 3 inclusive, 7 exclusive

array([3, 4, 5, 6])

In [28]:
arr3[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
arr4 = arr3[3:7].copy()

In [30]:
arr4

array([3, 4, 5, 6])

In [31]:
arr4[:] = 549

In [32]:
arr4

array([549, 549, 549, 549])

In [33]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
arr1[0][1]

np.float64(2.0)

In [36]:
arr1[0,1]

np.float64(2.0)

In [37]:
arr1[0] / 2

array([0.5, 1. , 1.5])

In [38]:
arr4 = arr1[:,1] ** 2

In [39]:
arr4

array([ 4., 25.])

In [40]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [41]:
arr1[1,1:3]

array([5., 6.])

In [42]:
arr1[:,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
# Boolean Indexing
names = np.array(['jack','kate','james','ben','jack','hugo','jack'])

In [44]:
names

array(['jack', 'kate', 'james', 'ben', 'jack', 'hugo', 'jack'],
      dtype='<U5')

In [45]:
mask = names == 'jack'

In [46]:
mask

array([ True, False, False, False,  True, False,  True])

In [47]:
arr5 = np.array([4,8,15,16,23,42,108])

In [48]:
arr5[2:5]

array([15, 16, 23])

In [49]:
arr5[mask]

array([  4,  23, 108])

In [50]:
arr5[arr5 >16]

array([ 23,  42, 108])

In [51]:
arr6 = arr5[:4]
arr6[arr6 % 2 == 0]

array([ 4,  8, 16])

In [52]:
arr5[:4][arr5[:4] %2 == 0]

array([ 4,  8, 16])

In [53]:
arr7 = np.arange(16).reshape((4,4))
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# fancy indexing
arr7[[1,3,2],[0,3,2]] # arr7[1,0] arr7[3,3] arr7[2,2] 

array([ 4, 15, 10])

In [55]:
def gun(*a): # variable number of argument
  return sum(a)

In [56]:
gun(1,2,3,4,5,6)

21

In [57]:
gun(1,2,3)

6

In [58]:
def sun(t):
  return sum(t)

In [59]:
sun((1,2,3))

6

In [60]:
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
arr7.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [62]:
arr7 * arr7.T

array([[  0,   4,  16,  36],
       [  4,  25,  54,  91],
       [ 16,  54, 100, 154],
       [ 36,  91, 154, 225]])

In [63]:
np.dot(arr7.T, arr7)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])